name: Security Check - Bandit for Python

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bandit Setup
      uses: ./
      with:
        python_version: '3.10'
        project_path: ./app/
        ignore_failure: true

    - name: Python Version
      run: python -c "import sys; print(sys.version)"
  
    - name: Bandit Report
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security Report
        path: output/security_report.txt
