name: Security Check - Bandit for Python

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      # security-events: write

    steps:
      - name: Setup GitHub Actions
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Install Bandit
        run: pip3 install bandit

      - name: Run Bandit
        run: bandit -r ./app/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        # if: failure()
        with:
          name: Security Report
          path: output/security_report.txt
