name: Security Check - Checkov for Terraform

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - name: Python Version
      run: python -c "import sys; print(sys.version)"

    - name: Checkov Report
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./iac/
        framework: terraform
